### ISSUE TITLE
Moving Pet Names into another file

### ISSUE THREAD

**Issue by InternetRamen** [jrwren/petname-js#3]
Could I contribute to this repo?

I really want a pet and I think this project is awesome!

I would like to move the pet names and adjectives to another file to make index.js cleaner. I also could do anything else you may want that is in my ability.

**Comment by jrwren** [comment]
I'm rather picky. How would it make things cleaner?

I consider this project done, but if you think you can do some fun things I would accept a PR. I probably won't accept anything that is for tidying up or cleaning as I don't share the same standards that many have about these things.

**Comment by InternetRamen** [comment]
Alright, I understand. I would try to add a better UI however I do not know if there is an HTML or CSS file in the repo. Thank you for responding!

**Comment by jrwren** [comment]
Ah yes, this repo is just an NPM module. It does not have a UI. I don't have the https://petnames.glitch.me UI on github.

**Comment by InternetRamen** [comment]
Alright, thank you for responding.
